language: ruby
sudo: false
cache: bundler
bundler_args: --retry=3 --jobs=3
before_install:
  - nvm install node
install:
  - npm install
before_script:
  - mysql -e 'CREATE DATABASE jobs_ruby_tw_test;' -u root
  - bin/setup
  - bin/rake db:test:prepare
rvm:
  - 2.7.2
matrix:
  fast_finish: true
services:
  - mysql
