language: ruby
rvm:
  - 2.0.0
  - 1.9.3
bundler_args: '--without development'
before_install:
  - gem install bundler --version '>= 1.3.0'
before_script:
  - cp config/database.yml.example config/database.yml
  - RAILS_ENV=test bin/rake db:create
  - RAILS_ENV=test bin/rake db:schema:load
