# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.
defaults: &defaults
  app_name: Ruby Jobs in Taiwan
  domain: http://jobsrubytw.dev
  mail_from: noreply@ruby.tw
  default_logo_url: /logo.png
  google_analytics_key:
  action_mailer:
    delivery_method: sendmail
  facebook_app_id:
  facebook_secret:

development:
  <<: *defaults
  secret_key_base: f6687ad9e66adfd5c25f4823b680f312b180f9928e08cbda73f4fb212d756b9c8505ce0c0cd916f3eccfc9553a96c3e32cdffcdfec23b4fcc0e9a68ed6fdabaa
  
test:
  <<: *defaults
  secret_key_base: cc7abb6dc8f12a38b8435259384a9300d0d80e9b55d6b657ed30f2f54f2c6f39e73bbd7839c12c1352efbf7c55ef7c65313cb365e83cbaee1a511a0c355fe1f9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  <<: *defaults
  domain:
  action_mailer:
    delivery_method: :smtp
    perform_deliveries: true
    raise_delivery_errors: true
  admin_emails:
  exception_notification_mailer:
    email_prefix:
    sender_address:
    exception_recipients:
